/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VehiclesRouteImport } from './routes/vehicles'
import { Route as RidesRouteImport } from './routes/rides'
import { Route as RevenueRouteImport } from './routes/revenue'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as DriversRouteImport } from './routes/drivers'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as ChargingRouteImport } from './routes/charging'
import { Route as IndexRouteImport } from './routes/index'

const VehiclesRoute = VehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const RidesRoute = RidesRouteImport.update({
  id: '/rides',
  path: '/rides',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenueRoute = RevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversRoute = DriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ChargingRoute = ChargingRouteImport.update({
  id: '/charging',
  path: '/charging',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/charging': typeof ChargingRoute
  '/customers': typeof CustomersRoute
  '/drivers': typeof DriversRoute
  '/pricing': typeof PricingRoute
  '/revenue': typeof RevenueRoute
  '/rides': typeof RidesRoute
  '/vehicles': typeof VehiclesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/charging': typeof ChargingRoute
  '/customers': typeof CustomersRoute
  '/drivers': typeof DriversRoute
  '/pricing': typeof PricingRoute
  '/revenue': typeof RevenueRoute
  '/rides': typeof RidesRoute
  '/vehicles': typeof VehiclesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/charging': typeof ChargingRoute
  '/customers': typeof CustomersRoute
  '/drivers': typeof DriversRoute
  '/pricing': typeof PricingRoute
  '/revenue': typeof RevenueRoute
  '/rides': typeof RidesRoute
  '/vehicles': typeof VehiclesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/charging'
    | '/customers'
    | '/drivers'
    | '/pricing'
    | '/revenue'
    | '/rides'
    | '/vehicles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/charging'
    | '/customers'
    | '/drivers'
    | '/pricing'
    | '/revenue'
    | '/rides'
    | '/vehicles'
  id:
    | '__root__'
    | '/'
    | '/charging'
    | '/customers'
    | '/drivers'
    | '/pricing'
    | '/revenue'
    | '/rides'
    | '/vehicles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChargingRoute: typeof ChargingRoute
  CustomersRoute: typeof CustomersRoute
  DriversRoute: typeof DriversRoute
  PricingRoute: typeof PricingRoute
  RevenueRoute: typeof RevenueRoute
  RidesRoute: typeof RidesRoute
  VehiclesRoute: typeof VehiclesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vehicles': {
      id: '/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rides': {
      id: '/rides'
      path: '/rides'
      fullPath: '/rides'
      preLoaderRoute: typeof RidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenue': {
      id: '/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof RevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers': {
      id: '/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof DriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charging': {
      id: '/charging'
      path: '/charging'
      fullPath: '/charging'
      preLoaderRoute: typeof ChargingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChargingRoute: ChargingRoute,
  CustomersRoute: CustomersRoute,
  DriversRoute: DriversRoute,
  PricingRoute: PricingRoute,
  RevenueRoute: RevenueRoute,
  RidesRoute: RidesRoute,
  VehiclesRoute: VehiclesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
